import sys
#try: color = sys.stdout.shell
#except AttributeError: raise RuntimeError("Use IDLE")
color = sys.stdout.shell
"""
#color.write("1) BLACK\n","SYNC")
#color.write("2) BLACK\n","stdin")
#color.write("3) PURPLE\n","BUILTIN")
#color.write("4) GREEN\n","STRING")
#color.write("5) DARK RED\n","console")
#color.write("6) RED\n","COMMENT")
#color.write("7) BLUE\n","stdout")
#color.write("8) BLACK\n","TODO")
#color.write("9) red\n","stderr")
color.write("10) white on BLACK\n","hit")
#color.write("11) BLUE\n","DEFINITION")
#color.write("12) ORANGE\n","KEYWORD")
color.write("13) black on RED\n","ERROR")
color.write("14) black on GRAY\n","sel")
print("")
"""
invad = alien = 1
fps = 5000000
mem = 0
ligne = "                                        "
pos = "ERROR"
pos1 = "sel"
neg = "hit"
x = 10
y = 10
h = 1
v = 1
xx = 33
yy = 33
hh = 1
vv = 1

while(invad > 0):
    for i in range(y-1):
            color.write("\n",neg)
    if invad == 1:
        frm = 5
        #type 0
        color.write(ligne[0:x]+"  ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write(" ",pos)
        color.write("   ",neg)
        color.write(" ",pos)
        color.write("  \n\n",neg)

    if invad == 2:
        #type 1
        frm = 5
        color.write("\n  ",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)

    if invad == 3:
        #Type 2
        frm = 5
        color.write("\n ",neg)
        color.write(ligne[0:x]+" ", neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)

    if invad == 5:
        #Type 3
        frm = 5
        color.write("\n  ",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)

    if invad == 4:
        #Type 4
        frm = 5
        color.write("\n  ",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write("  ",neg)
        color.write(" ",pos)
        color.write("  ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)

    if invad == 6:
        #Type 5
        frm = 5
        color.write("\n  ",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("     ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write("     ",neg)
        color.write(" ",pos)
        color.write("\n",neg)

    if invad == 7:
        #Space invader1
        frm = 8
        color.write("\n   ",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("    ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("      ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write("        ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write("      ",neg)
        color.write(" ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write(" ",pos)
        color.write("    ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)

    if invad == 8:
        #Space invader2
        frm = 8
        color.write("\n   ",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("    ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("      ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write("        ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write(" ",pos)
        color.write("  ",neg)
        color.write(" ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("  ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("\n",neg)

    if invad == 9:
        #space invader3
        frm = 8
        color.write("\n  ",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write("     ", neg)
        color.write(" ",pos)
        color.write("  \n", neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write(" ",pos)
        color.write("   ", neg)
        color.write(" ",pos)
        color.write("   \n", neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("       ",pos)
        color.write("  \n", neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("  ",pos)
        color.write(" ", neg)
        color.write("   ",pos)
        color.write(" ",neg)
        color.write("  ", pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("           ", pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("       ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("     ",neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write(" ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write("   \n",neg)

    if invad == 10:
        #space invader4
        frm = 8
        color.write("\n  ",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write("     ", neg)
        color.write(" ",pos)
        color.write("  \n", neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write("  ",neg)
        color.write(" ",pos)
        color.write("   ", neg)
        color.write(" ",pos)
        color.write("  ", neg)
        color.write(" ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write(" ",pos)
        color.write(" ",neg)
        color.write("       ",pos)
        color.write(" ", neg)
        color.write(" ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("   ",pos)
        color.write(" ", neg)
        color.write("   ",pos)
        color.write(" ",neg)
        color.write("   ", pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("           ", pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("         ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write(" ",pos)
        color.write("     ",neg)
        color.write(" ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write(" ",pos)
        color.write("       ",neg)
        color.write(" ",pos)
        color.write(" \n",neg)

    if invad == 11:
        #space invader5
        frm = 8
        color.write("\n    ",neg)
        color.write(ligne[0:x],neg)
        color.write("    ",pos)
        color.write("    \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("          ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("            ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write("   ",pos)
        color.write("  ",neg)
        color.write("  ",pos)
        color.write("  ",neg)
        color.write("   ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write("            ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("   ",pos)
        color.write("  ",neg)
        color.write("   ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("  ",pos)
        color.write("  ",neg)
        color.write("  ",pos)
        color.write("  ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("  ",pos)
        color.write("    ",neg)
        color.write("  ",pos)
        color.write("  \n",neg)

    if invad == 12:
        #space invader6
        frm = 8
        color.write("\n    ",neg)
        color.write(ligne[0:x],neg)
        color.write("    ",pos)
        color.write("    \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("          ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("            ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write("   ",pos)
        color.write("  ",neg)
        color.write("  ",pos)
        color.write("  ",neg)
        color.write("   ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x],neg)
        color.write("            ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write("  ",pos)
        color.write("  ",neg)
        color.write("  ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x],neg)
        color.write("  ",pos)
        color.write("        ",neg)
        color.write("  ",pos)
        color.write("\n",neg)
        
    if invad == 13:
        #sapce invader7
        frm = 7
        color.write("\n      ",neg)
        color.write(ligne[0:x],neg)
        color.write("    ",pos)
        color.write("      \n",neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write("          ",pos)
        color.write("   \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("            ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" ",neg)
        color.write("  ",pos)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("                ",pos)
        color.write("\n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("   ",pos)
        color.write("  ",neg)
        color.write("  ",pos)
        color.write("  ",neg)
        color.write("   ",pos)
        color.write("  \n",neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write(" ",pos)
        color.write("        ",neg)
        color.write(" ",pos)
        color.write("   \n",neg)

    if invad == 14:
        #sapce invader7
        frm = 7
        color.write("\n      ",neg)
        color.write(ligne[0:x],neg)
        color.write("    ",pos1)
        color.write("      \n",neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write("          ",pos1)
        color.write("   \n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("            ",pos1)
        color.write("  \n",neg)
        color.write(ligne[0:x]+" ",neg)
        color.write("  ",pos1)
        color.write(" ",neg)
        color.write("  ",pos1)
        color.write(" ",neg)
        color.write("  ",pos1)
        color.write(" ",neg)
        color.write("  ",pos1)
        color.write(" ",neg)
        color.write("  ",pos1)
        color.write(" \n",neg)
        color.write(ligne[0:x],neg)
        color.write("                ",pos1)
        color.write("\n",neg)
        color.write(ligne[0:x]+"  ",neg)
        color.write("   ",pos1)
        color.write("  ",neg)
        color.write("  ",pos1)
        color.write("  ",neg)
        color.write("   ",pos1)
        color.write("  \n",neg)
        color.write(ligne[0:x]+"   ",neg)
        color.write(" ",pos1)
        color.write("        ",neg)
        color.write(" ",pos1)
        color.write("   \n",neg)
        
    if invad == 15:
        #color.write("","sel")
        frm = 2
        color.write("\n      GAME OVER DUDE\n","KEYWORD")
        print("Do you want to play again?")
        color.write("        YES","STRING")
        color.write(" or ","KEYWORD")
        color.write("NO\n","COMMENT")
        
    for i in range((30 - frm) -(y - 1)):
        color.write("\n",neg)

    #key = input()
    for iii in range(fps):
        fps = fps
        
    x = x + (3*h)
    y = y + v

    #xx = xx + (3*hh)
    #yy = yy + vv

    invad = invad + 1
    
    if(x > 48 or x < 2):
        h = -h
        alien = alien + 2
    if(y > 20 or y < 2):
        v = -v
    """
    if(xx > 48 or xx < 1):
        hh = -hh
    if(yy > 32 or yy < 17):
        vv = -vv
    """
    if(invad > alien+1):
        invad = alien
    if(invad > 14):
        invad = alien = 1
        mem = pos
        pos = pos1
        pos1 = mem
        
